export const EU_COUNTRIES = [
  { code: "DE", label: "Germany", shortLabel: "DE" },
  { code: "EU27_2020", label: "European Union", shortLabel: "EU" },
  { code: "FR", label: "France", shortLabel: "FR" },
  { code: "IT", label: "Italy", shortLabel: "IT" },
  { code: "NL", label: "Netherlands", shortLabel: "NL" },
  { code: "PL", label: "Poland", shortLabel: "PL" },
];

export const GLOBAL_COUNTRIES = [
  { code: "DEU", label: "Germany", shortLabel: "DE" },
  { code: "EUU", label: "European Union", shortLabel: "EU" },
  { code: "FRA", label: "France", shortLabel: "FR" },
  { code: "ITA", label: "Italy", shortLabel: "IT" },
  { code: "NLD", label: "Netherlands", shortLabel: "NL" },
  { code: "POL", label: "Poland", shortLabel: "PL" },
  { code: "USA", label: "United States", shortLabel: "US" },
  { code: "CHN", label: "China", shortLabel: "CN" },
];

export const PILLARS = [
  {
    id: "productivity",
    name: "Productivity & growth",
    description:
      "Whether output per unit of labour is improving—not simply whether headline GDP is expanding.",
  },
  {
    id: "industry",
    name: "Industrial engine",
    description:
      "Manufacturing production, capacity and economic structure: the operating core of Germany's tradable economy.",
  },
  {
    id: "costs",
    name: "Cost position & energy",
    description:
      "Unit labour costs and industrial energy prices, always read alongside productivity and demand.",
  },
  {
    id: "trade",
    name: "Trade & economic security",
    description:
      "Export performance, sector mix and exposure to concentrated markets or critical foreign inputs.",
  },
  {
    id: "investment",
    name: "Investment & capital",
    description:
      "Whether public and private capital is expanding the economy's future productive capacity.",
  },
  {
    id: "innovation",
    name: "Innovation & digital diffusion",
    description:
      "Research effort, high-technology output and the spread of enabling digital capabilities.",
  },
  {
    id: "labour",
    name: "Labour, skills & demography",
    description:
      "Labour availability, utilisation and the slow-moving demographic constraint on potential growth.",
  },
  {
    id: "state",
    name: "State capacity & infrastructure",
    description:
      "Public investment and institutional capacity to turn finance and policy into productive assets.",
  },
];

const EUROSTAT_BASE = "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data";

export const EUROSTAT_INDICATORS = [
  {
    id: "real-gdp-qoq",
    name: "Real GDP growth",
    pillar: "productivity",
    dataset: "namq_10_gdp",
    filters: { na_item: "B1GQ", unit: "CLV_PCH_PRE", s_adj: "SCA" },
    frequency: "Quarterly",
    direction: "higher",
    noise: 0.2,
    decimals: 1,
    suffix: "%",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/namq_10_gdp?lang=en` },
  },
  {
    id: "productivity-hourly",
    name: "Real productivity per hour",
    pillar: "productivity",
    dataset: "namq_10_lp_ulc",
    filters: { na_item: "RLPR_HW", unit: "PCH_PRE", s_adj: "SCA" },
    frequency: "Quarterly",
    direction: "higher",
    noise: 0.2,
    decimals: 1,
    suffix: "%",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/namq_10_lp_ulc?lang=en` },
  },
  {
    id: "unit-labour-cost",
    name: "Nominal unit labour cost index",
    pillar: "costs",
    dataset: "namq_10_lp_ulc",
    filters: { na_item: "NULC_HW", unit: "I20", s_adj: "SCA" },
    frequency: "Quarterly",
    direction: "lower",
    noise: 0.5,
    decimals: 1,
    suffix: "",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/namq_10_lp_ulc?lang=en` },
  },
  {
    id: "industrial-electricity-price",
    name: "Industrial electricity price",
    pillar: "costs",
    dataset: "nrg_pc_205",
    filters: {
      currency: "EUR",
      tax: "X_TAX",
      unit: "KWH",
      nrg_cons: "MWH2000-19999",
      siec: "E7000",
    },
    frequency: "Semiannual",
    direction: "lower",
    noise: 0.005,
    decimals: 3,
    suffix: " €/kWh",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/nrg_pc_205?lang=en` },
  },
  {
    id: "industrial-gas-price",
    name: "Industrial gas price",
    pillar: "costs",
    dataset: "nrg_pc_203",
    filters: {
      currency: "EUR",
      tax: "X_TAX",
      unit: "KWH",
      nrg_cons: "GJ100000-999999",
      siec: "G3000",
    },
    frequency: "Semiannual",
    direction: "lower",
    noise: 0.005,
    decimals: 3,
    suffix: " €/kWh",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/nrg_pc_203?lang=en` },
  },
  {
    id: "industrial-production",
    name: "Industrial production",
    pillar: "industry",
    dataset: "sts_inpr_m",
    filters: { indic_bt: "PRD", nace_r2: "B-D", s_adj: "SCA", unit: "I21" },
    frequency: "Monthly",
    direction: "higher",
    noise: 1,
    decimals: 1,
    suffix: "",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/sts_inpr_m?lang=en` },
  },
  {
    id: "unemployment",
    name: "Unemployment rate",
    pillar: "labour",
    dataset: "une_rt_m",
    filters: { sex: "T", age: "TOTAL", unit: "PC_ACT", s_adj: "SA" },
    frequency: "Monthly",
    direction: "lower",
    noise: 0.1,
    decimals: 1,
    suffix: "%",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/une_rt_m?lang=en` },
  },
  {
    id: "investment-share",
    name: "Gross fixed capital formation",
    pillar: "investment",
    dataset: "nama_10_gdp",
    filters: { na_item: "P51G", unit: "PC_GDP" },
    frequency: "Annual",
    direction: "structural-higher",
    noise: 0.5,
    decimals: 1,
    suffix: "% GDP",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/nama_10_gdp?lang=en` },
  },
  {
    id: "rd-intensity-eu",
    name: "R&D expenditure",
    pillar: "innovation",
    dataset: "rd_e_gerdtot",
    filters: { sectperf: "TOTAL", unit: "PC_GDP" },
    frequency: "Annual",
    direction: "structural-higher",
    noise: 0.1,
    decimals: 1,
    suffix: "% GDP",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/rd_e_gerdtot?lang=en` },
  },
  {
    id: "old-age-dependency-eu",
    name: "Old-age dependency ratio",
    pillar: "labour",
    dataset: "demo_pjanind",
    filters: { indic_de: "OLDDEP1" },
    frequency: "Annual",
    direction: "structural-lower",
    noise: 0.5,
    decimals: 1,
    suffix: "%",
    source: { name: "Eurostat", url: `${EUROSTAT_BASE}/demo_pjanind?lang=en` },
  },
];

const WORLD_BANK_BASE = "https://api.worldbank.org/v2";

export const WORLD_BANK_INDICATORS = [
  {
    id: "global-gdp-growth",
    code: "NY.GDP.MKTP.KD.ZG",
    name: "Real GDP growth",
    pillar: "productivity",
    direction: "structural-higher",
    noise: 0.2,
    decimals: 1,
    suffix: "%",
  },
  {
    id: "global-productivity",
    code: "SL.GDP.PCAP.EM.KD",
    name: "GDP per person employed",
    pillar: "productivity",
    direction: "structural-higher",
    noise: 500,
    decimals: 0,
    suffix: " int$",
  },
  {
    id: "global-investment",
    code: "NE.GDI.FTOT.ZS",
    name: "Gross capital formation",
    pillar: "investment",
    direction: "structural-higher",
    noise: 0.5,
    decimals: 1,
    suffix: "% GDP",
  },
  {
    id: "global-rd",
    code: "GB.XPD.RSDV.GD.ZS",
    name: "R&D expenditure",
    pillar: "innovation",
    direction: "structural-higher",
    noise: 0.1,
    decimals: 1,
    suffix: "% GDP",
  },
  {
    id: "global-fdi",
    code: "BX.KLT.DINV.WD.GD.ZS",
    name: "FDI net inflows",
    pillar: "investment",
    direction: "neutral",
    noise: 0.5,
    decimals: 1,
    suffix: "% GDP",
  },
  {
    id: "global-manufacturing",
    code: "NV.IND.MANF.ZS",
    name: "Manufacturing value added",
    pillar: "industry",
    direction: "neutral",
    noise: 0.5,
    decimals: 1,
    suffix: "% GDP",
  },
  {
    id: "global-high-tech-exports",
    code: "TX.VAL.TECH.MF.ZS",
    name: "High-tech exports",
    pillar: "trade",
    direction: "structural-higher",
    noise: 0.5,
    decimals: 1,
    suffix: "%",
  },
  {
    id: "global-working-age",
    code: "SP.POP.1564.TO.ZS",
    name: "Working-age population",
    pillar: "labour",
    direction: "structural-higher",
    noise: 0.5,
    decimals: 1,
    suffix: "%",
  },
  {
    id: "global-old-age",
    code: "SP.POP.DPND.OL",
    name: "Old-age dependency",
    pillar: "labour",
    direction: "structural-lower",
    noise: 0.5,
    decimals: 1,
    suffix: "%",
  },
  {
    id: "global-broadband",
    code: "IT.NET.BBND.P2",
    name: "Fixed broadband subscriptions",
    pillar: "state",
    direction: "structural-higher",
    noise: 0.5,
    decimals: 1,
    suffix: " /100",
  },
].map((definition) => ({
  ...definition,
  frequency: "Annual",
  source: {
    name: "World Bank WDI",
    url: `${WORLD_BANK_BASE}/indicator/${definition.code}`,
  },
}));

export const NEWS_SOURCES = [
  {
    id: "destatis",
    name: "Destatis",
    kind: "official-statistics",
    authority: 4,
    url: "https://www.destatis.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/Aktuell.xml",
  },
  {
    id: "bundesbank",
    name: "Deutsche Bundesbank",
    kind: "official-policy",
    authority: 3,
    url: "https://www.bundesbank.de/service/rss/de/633290/feed.rss",
  },
  {
    id: "bundesbank-press",
    name: "Deutsche Bundesbank · Press",
    kind: "official-policy",
    authority: 3,
    url: "https://www.bundesbank.de/service/rss/de/633286/feed.rss",
  },
  {
    id: "sap",
    name: "SAP News",
    kind: "company",
    authority: 1,
    url: "https://news.sap.com/germany/feed/",
  },
];

export const METHODOLOGY = {
  noiseBands: [
    { label: "GDP, productivity and unit labour costs", value: "0.2 percentage points" },
    { label: "Industrial production", value: "1 index point" },
    { label: "Unemployment", value: "0.1 percentage points" },
    { label: "Annual ratios", value: "0.5 percentage points" },
  ],
};
